# Generated by Django 3.0.6 on 2020-06-12 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category_new',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_posts', to='recipes.Category'),
        ),
        migrations.RemoveField(
            model_name='post',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='post',
            name='ingredients',
            field=models.TextField(default=''),
        ),
    ]
