# Generated by Django 3.0.6 on 2020-06-08 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_auto_20200608_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientandamount',
            name='amount_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.AmountType'),
        ),
        migrations.AlterField(
            model_name='ingredientandamount',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.Ingredient'),
        ),
    ]
