# Generated by Django 3.0.6 on 2020-06-10 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0002_recipe_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_report',
            name='reported_user',
            field=models.BigIntegerField(),
        ),
    ]
