# Generated by Django 3.0.6 on 2020-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_auto_20200610_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_report',
            name='reported_user',
            field=models.CharField(max_length=100),
        ),
    ]
