# Generated by Django 3.0.6 on 2020-06-10 20:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0006_auto_20200610_2319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_report',
            name='reported_post',
        ),
    ]
