# Generated by Django 3.0.6 on 2020-06-10 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0007_remove_recipe_report_reported_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe_report',
            name='reported_post',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='recipes.Post'),
        ),
    ]
