# Generated by Django 3.0.6 on 2020-06-07 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
